import DashboardLayout from "@/components/DashboardLayout";
import { Seo } from "@/components/Seo";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BarChart3, CheckCircle2, ClipboardList, FileSearch, Handshake, Target, UsersRound } from "lucide-react";
import React from "react";

function words(value: string) { return value.replace(/_/g, " ").replace(/\b\w/g, (character) => character.toUpperCase()); }
function currency(cents: number) { return new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100); }

export default function Reports() {
  const { isAuthenticated } = useAuth(); const reportQuery = trpc.reports.overview.useQuery(undefined, { enabled: isAuthenticated, retry: false }); const report = reportQuery.data;
  if (reportQuery.isLoading) return <DashboardLayout><Seo title="Reports" description="Owner-scoped operational reporting for contacts, deals, tasks, campaigns, and documents." /><div className="py-16 text-center text-sm font-bold text-[#74798d]">Calculating operational reports…</div></DashboardLayout>;
  if (reportQuery.isError) return <DashboardLayout><Seo title="Reports" description="Owner-scoped operational reporting for contacts, deals, tasks, campaigns, and documents." /><section role="alert" className="mx-auto mt-12 max-w-xl rounded-[1.35rem] border border-[#b66b58]/20 bg-[#fff7f3] p-8 text-center shadow-[0_18px_45px_rgba(26,30,59,.06)]"><p className="font-sans text-[0.65rem] font-extrabold uppercase tracking-[.14em] text-[#a05b4b]">Reports unavailable</p><h1 className="mt-2 text-3xl text-[#303657]">We could not calculate this workspace report.</h1><p className="mt-3 text-sm leading-6 text-[#74798e]">No reporting data was changed. Please try again after the connection is available.</p><button type="button" onClick={() => reportQuery.refetch()} className="ss-button-primary mt-5">Try again</button></section></DashboardLayout>;
  if (!report) return <DashboardLayout><Seo title="Reports" description="Owner-scoped operational reporting for contacts, deals, tasks, campaigns, and documents." /><section className="mx-auto mt-12 max-w-xl rounded-[1.35rem] border border-[#171b39]/9 bg-white p-8 text-center shadow-[0_18px_45px_rgba(26,30,59,.06)]"><p className="font-sans text-[0.65rem] font-extrabold uppercase tracking-[.14em] text-[#8a6c45]">No report payload</p><h1 className="mt-2 text-3xl text-[#303657]">No reporting data is available yet.</h1><p className="mt-3 text-sm leading-6 text-[#74798e]">Create CRM records or refresh the page when your workspace data is ready.</p></section></DashboardLayout>;
  const stageMax = Math.max(1, ...report.stageCounts.map((item) => item.valueCents || item.count)); const statusMax = Math.max(1, ...report.contactStatusCounts.map((item) => item.count));
  return <DashboardLayout><Seo title="Reports" description="Owner-scoped operational reporting for contacts, deals, tasks, campaigns, and documents." />
    <section><p className="font-sans text-xs font-extrabold uppercase tracking-[.14em] text-[#8a6c45]">Operations · reports</p><h1 className="mt-2 text-4xl leading-tight text-[#202547] sm:text-5xl">See the work, not a projection.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#697087]">These measures are calculated from your own contacts, deals, tasks, documents, and campaign plans. No sample activity is included.</p></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-[1.2rem] border border-[#171b39]/9 bg-white p-5 shadow-[0_14px_38px_rgba(26,30,59,.05)]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8edf7] text-[#42567f]"><Handshake size={19} /></span><p className="mt-5 font-sans text-[0.62rem] font-extrabold uppercase tracking-[.12em] text-[#7a7f93]">Active pipeline</p><p className="mt-1 text-2xl font-semibold text-[#2b3053]">{currency(report.pipelineValueCents)}</p><p className="mt-1 text-xs text-[#73798f]">Across {report.activeDealCount} open deals.</p></article><article className="rounded-[1.2rem] border border-[#171b39]/9 bg-white p-5 shadow-[0_14px_38px_rgba(26,30,59,.05)]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f1ece0] text-[#8a6c45]"><UsersRound size={19} /></span><p className="mt-5 font-sans text-[0.62rem] font-extrabold uppercase tracking-[.12em] text-[#7a7f93]">Eligible contacts</p><p className="mt-1 text-2xl font-semibold text-[#2b3053]">{report.eligibleContactCount}</p><p className="mt-1 text-xs text-[#73798f]">From {report.contactCount} total CRM contacts.</p></article><article className="rounded-[1.2rem] border border-[#171b39]/9 bg-white p-5 shadow-[0_14px_38px_rgba(26,30,59,.05)]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f7e9e3] text-[#9b5c45]"><ClipboardList size={19} /></span><p className="mt-5 font-sans text-[0.62rem] font-extrabold uppercase tracking-[.12em] text-[#7a7f93]">Open tasks</p><p className="mt-1 text-2xl font-semibold text-[#2b3053]">{report.openTaskCount}</p><p className="mt-1 text-xs text-[#73798f]">{report.overdueTaskCount} currently overdue.</p></article><article className="rounded-[1.2rem] bg-[#22294e] p-5 text-white shadow-[0_18px_45px_rgba(26,30,59,.15)]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/8 text-[#dfcda9]"><Target size={19} /></span><p className="mt-5 font-sans text-[0.62rem] font-extrabold uppercase tracking-[.12em] text-[#d8cda9]">Operational plans</p><p className="mt-1 text-2xl font-semibold">{report.campaignPlanCount}</p><p className="mt-1 text-xs text-[#d5d4df]">Campaign plans remain delivery-safe.</p></article></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-[1.35rem] border border-[#171b39]/9 bg-white p-5 shadow-[0_18px_45px_rgba(26,30,59,.06)]"><div className="flex items-start justify-between gap-3"><div><p className="font-sans text-[0.62rem] font-extrabold uppercase tracking-[.13em] text-[#8a6c45]">Pipeline distribution</p><h2 className="mt-1 text-2xl text-[#2d3255]">Where deal value is currently held.</h2></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8edf7] text-[#42567f]"><BarChart3 size={18} /></span></div>{report.stageCounts.length === 0 ? <div className="py-16 text-center"><p className="font-semibold text-[#343a5e]">No deal stages to report yet.</p><p className="mt-2 text-sm text-[#74798e]">Create a contact-linked deal to start building a real pipeline view.</p></div> : <div className="mt-7 space-y-5">{report.stageCounts.map((item) => { const scale = (item.valueCents || item.count) / stageMax * 100; return <div key={item.stage}><div className="flex items-center justify-between gap-3 text-sm"><span className="font-extrabold text-[#454b6b]">{words(item.stage)}</span><span className="text-xs text-[#70758a]">{item.count} deals · {currency(item.valueCents)}</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-[#eeeef3]"><div className="h-full rounded-full bg-gradient-to-r from-[#547296] to-[#9ab2c9]" style={{ width: `${Math.max(6, scale)}%` }} /></div></div>; })}</div>}</article><article className="rounded-[1.35rem] border border-[#171b39]/9 bg-white p-5 shadow-[0_18px_45px_rgba(26,30,59,.06)]"><div className="flex items-start justify-between gap-3"><div><p className="font-sans text-[0.62rem] font-extrabold uppercase tracking-[.13em] text-[#8a6c45]">Contact mix</p><h2 className="mt-1 text-2xl text-[#2d3255]">Status distribution in the CRM.</h2></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f1ece0] text-[#8a6c45]"><UsersRound size={18} /></span></div>{report.contactStatusCounts.length === 0 ? <div className="py-16 text-center"><p className="font-semibold text-[#343a5e]">No contact statuses set.</p><p className="mt-2 text-sm text-[#74798e]">Optional ISA statuses will appear here as contacts are classified.</p></div> : <div className="mt-7 space-y-4">{report.contactStatusCounts.map((item) => <div key={item.status}><div className="flex items-center justify-between gap-3 text-sm"><span className="font-extrabold text-[#454b6b]">{words(item.status)}</span><span className="text-xs text-[#70758a]">{item.count}</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-[#eeeef3]"><div className="h-full rounded-full bg-gradient-to-r from-[#b8956c] to-[#dec9a9]" style={{ width: `${Math.max(8, item.count / statusMax * 100)}%` }} /></div></div>)}</div>}</article></section>
    <section className="mt-5 grid gap-4 md:grid-cols-3"><article className="rounded-[1.2rem] border border-[#171b39]/9 bg-white p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf4eb] text-[#557450]"><CheckCircle2 size={17} /></span><h3 className="mt-4 text-lg text-[#303657]">Closed outcomes</h3><p className="mt-2 text-2xl font-semibold text-[#2b3053]">{report.closedDealCount}</p><p className="mt-1 text-xs leading-5 text-[#74798e]">Deals currently recorded in the Closed stage.</p></article><article className="rounded-[1.2rem] border border-[#171b39]/9 bg-white p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f7e9e3] text-[#9b5c45]"><FileSearch size={17} /></span><h3 className="mt-4 text-lg text-[#303657]">Document review</h3><p className="mt-2 text-2xl font-semibold text-[#2b3053]">{report.documentReviewCount}</p><p className="mt-1 text-xs leading-5 text-[#74798e]">Tracked documents awaiting an internal review state.</p></article><article className="rounded-[1.2rem] border border-[#171b39]/9 bg-white p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8edf7] text-[#42567f]"><Target size={17} /></span><h3 className="mt-4 text-lg text-[#303657]">Report boundary</h3><p className="mt-2 text-sm font-semibold text-[#434a6b]">Workspace-scoped, live aggregates.</p><p className="mt-1 text-xs leading-5 text-[#74798e]">Every metric above is calculated from the current owner’s records only.</p></article></section>
  </DashboardLayout>;
}
