/* @vitest-environment jsdom */
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import React from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const trpcMocks = vi.hoisted(() => ({ createUseMutation: vi.fn(), listUseQuery: vi.fn(), setStatusUseMutation: vi.fn(), useUtils: vi.fn() }));
vi.mock("@/components/DashboardLayout", () => ({ default: ({ children }: { children: React.ReactNode }) => <div>{children}</div> })); vi.mock("@/components/Seo", () => ({ Seo: () => null })); vi.mock("@/_core/hooks/useAuth", () => ({ useAuth: () => ({ isAuthenticated: true }) })); vi.mock("@/components/ui/dialog", () => ({ Dialog: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogContent: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogDescription: ({ children }: { children: React.ReactNode }) => <p>{children}</p>, DialogFooter: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogHeader: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogTitle: ({ children }: { children: React.ReactNode }) => <h2>{children}</h2> })); vi.mock("sonner", () => ({ toast: { error: vi.fn(), success: vi.fn() } }));
vi.mock("@/lib/trpc", () => ({ trpc: { useUtils: trpcMocks.useUtils, automations: { list: { useQuery: trpcMocks.listUseQuery }, create: { useMutation: trpcMocks.createUseMutation }, setStatus: { useMutation: trpcMocks.setStatusUseMutation } } } }));
import Automations from "../client/src/pages/Automations"; const create = vi.fn(); const setStatus = vi.fn();
beforeEach(() => { vi.clearAllMocks(); trpcMocks.useUtils.mockReturnValue({ automations: { list: { invalidate: vi.fn() } } }); trpcMocks.listUseQuery.mockReturnValue({ data: [{ id: 601, name: "Prospect follow-up", trigger: "contact_status_changed", action: "create_task", actionDetail: "Call within one day", status: "draft" }], isLoading: false }); trpcMocks.createUseMutation.mockReturnValue({ isPending: false, mutate: create }); trpcMocks.setStatusUseMutation.mockReturnValue({ isPending: false, mutate: setStatus }); }); afterEach(() => cleanup());
describe("Automations workspace", () => { it("creates a trigger-and-action rule without execution", () => { render(<Automations />); fireEvent.change(screen.getByLabelText("Rule name"), { target: { value: "New lead task" } }); fireEvent.change(screen.getByLabelText("When this happens"), { target: { value: "contact_created" } }); fireEvent.change(screen.getByLabelText("Then plan this"), { target: { value: "create_task" } }); fireEvent.click(within(screen.getByLabelText("Rule name").closest("form")!).getByRole("button", { name: "Create rule" })); expect(create).toHaveBeenCalledWith(expect.objectContaining({ name: "New lead task", trigger: "contact_created", action: "create_task", status: "draft" })); }); it("renders the trigger-action chain and controls lifecycle", () => { render(<Automations />); expect(screen.getAllByText("A contact status changes")[0]).toBeTruthy(); expect(screen.getAllByText("Create a follow-up task")[0]).toBeTruthy(); fireEvent.change(screen.getByLabelText("Update status for Prospect follow-up"), { target: { value: "paused" } }); expect(setStatus).toHaveBeenCalledWith({ ruleId: 601, status: "paused" }); }); });
