/* @vitest-environment jsdom */
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import React from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const trpcMocks = vi.hoisted(() => ({ campaignsListUseQuery: vi.fn(), contactsListUseQuery: vi.fn(), createUseMutation: vi.fn(), setStatusUseMutation: vi.fn(), useUtils: vi.fn() }));
vi.mock("@/components/DashboardLayout", () => ({ default: ({ children }: { children: React.ReactNode }) => <div>{children}</div> })); vi.mock("@/components/Seo", () => ({ Seo: () => null })); vi.mock("@/_core/hooks/useAuth", () => ({ useAuth: () => ({ isAuthenticated: true }) })); vi.mock("@/components/ui/dialog", () => ({ Dialog: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogContent: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogDescription: ({ children }: { children: React.ReactNode }) => <p>{children}</p>, DialogFooter: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogHeader: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogTitle: ({ children }: { children: React.ReactNode }) => <h2>{children}</h2> })); vi.mock("sonner", () => ({ toast: { error: vi.fn(), success: vi.fn() } }));
vi.mock("@/lib/trpc", () => ({ trpc: { useUtils: trpcMocks.useUtils, contacts: { list: { useQuery: trpcMocks.contactsListUseQuery } }, campaigns: { list: { useQuery: trpcMocks.campaignsListUseQuery }, create: { useMutation: trpcMocks.createUseMutation }, setStatus: { useMutation: trpcMocks.setStatusUseMutation } } } }));
import Marketing from "../client/src/pages/Marketing"; const create = vi.fn(); const setStatus = vi.fn();
beforeEach(() => { vi.clearAllMocks(); trpcMocks.useUtils.mockReturnValue({ campaigns: { list: { invalidate: vi.fn() } } }); trpcMocks.contactsListUseQuery.mockReturnValue({ data: [{ id: 1, status: "prospect" }, { id: 2, status: "active" }, { id: 3, status: "dnc" }], isLoading: false }); trpcMocks.campaignsListUseQuery.mockReturnValue({ data: [{ id: 501, name: "Spring valuations", objective: "Invite prospects", channel: "email", audienceRule: "prospect", status: "draft", scheduledAt: null }], isLoading: false }); trpcMocks.createUseMutation.mockReturnValue({ isPending: false, mutate: create }); trpcMocks.setStatusUseMutation.mockReturnValue({ isPending: false, mutate: setStatus }); }); afterEach(() => cleanup());
describe("Marketing workspace", () => { it("creates a campaign plan using a real contact audience rule", () => { render(<Marketing />); fireEvent.change(screen.getByLabelText("Campaign name"), { target: { value: "Summer check-in" } }); fireEvent.change(screen.getByLabelText("Audience"), { target: { value: "active" } }); fireEvent.change(screen.getByLabelText("Planned channel"), { target: { value: "mixed" } }); fireEvent.click(within(screen.getByLabelText("Campaign name").closest("form")!).getByRole("button", { name: "Create plan" })); expect(create).toHaveBeenCalledWith(expect.objectContaining({ name: "Summer check-in", audienceRule: "active", channel: "mixed", status: "draft" })); }); it("renders the audience context and controls campaign lifecycle", () => { render(<Marketing />); expect(screen.getByText("1 eligible contacts")).toBeTruthy(); fireEvent.change(screen.getByLabelText("Update status for Spring valuations"), { target: { value: "paused" } }); expect(setStatus).toHaveBeenCalledWith({ campaignId: 501, status: "paused" }); }); });
