import { beforeEach, describe, expect, it, vi } from "vitest";
const documentsDb = vi.hoisted(() => ({ createCrmDocument: vi.fn(), listCrmDocuments: vi.fn(), setCrmDocumentStatus: vi.fn() }));
vi.mock("./db", async () => ({ ...(await vi.importActual<typeof import("./db")>("./db")), ...documentsDb }));
import { appRouter } from "./routers";
const owner = { id: 41, openId: "documents-owner", name: "Document Owner", email: "owner@example.com", loginMethod: null, role: "admin" as const, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() };
function caller() { return appRouter.createCaller({ user: owner } as never); }
describe("Documents runtime contract", () => {
  beforeEach(() => { vi.resetAllMocks(); documentsDb.listCrmDocuments.mockResolvedValue([{ id: 401, ownerUserId: 41, contactId: 81, contactName: "Tiffany Hoskins", dealId: 91, dealTitle: "Main Street listing", name: "Seller disclosure package", documentType: "disclosure", status: "requested", dueAt: null, notes: null, createdAt: new Date(), updatedAt: new Date() }]); documentsDb.createCrmDocument.mockImplementation(async (input: unknown) => ({ id: 401, ...input as object, contactName: "Tiffany Hoskins", dealTitle: "Main Street listing", notes: null, createdAt: new Date(), updatedAt: new Date() })); documentsDb.setCrmDocumentStatus.mockImplementation(async (input: { documentId: number; status: string }) => ({ id: input.documentId, ownerUserId: 41, contactId: 81, contactName: "Tiffany Hoskins", dealId: 91, dealTitle: "Main Street listing", name: "Seller disclosure package", documentType: "disclosure", status: input.status, dueAt: null, notes: null, createdAt: new Date(), updatedAt: new Date() })); });
  it("creates an owner-scoped document record with optional connected context", async () => { const document = await caller().documents.create({ name: "Seller disclosure package", contactId: 81, dealId: 91, documentType: "disclosure", status: "requested" }); expect(documentsDb.createCrmDocument).toHaveBeenCalledWith(expect.objectContaining({ ownerUserId: 41, contactId: 81, dealId: 91, documentType: "disclosure" })); expect(document).toMatchObject({ contactName: "Tiffany Hoskins", dealTitle: "Main Street listing" }); });
  it("lists a scoped document tracker and updates its status", async () => { const listed = await caller().documents.list(); const updated = await caller().documents.setStatus({ documentId: 401, status: "approved" }); expect(documentsDb.listCrmDocuments).toHaveBeenCalledWith(41); expect(listed[0]).toMatchObject({ status: "requested" }); expect(documentsDb.setCrmDocumentStatus).toHaveBeenCalledWith({ ownerUserId: 41, documentId: 401, status: "approved" }); expect(updated).toMatchObject({ status: "approved" }); });
});
