/* @vitest-environment jsdom */
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import React from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const trpcMocks = vi.hoisted(() => ({ contactsListUseQuery: vi.fn(), createUseMutation: vi.fn(), dealsListUseQuery: vi.fn(), documentsListUseQuery: vi.fn(), setStatusUseMutation: vi.fn(), useUtils: vi.fn() }));
vi.mock("@/components/DashboardLayout", () => ({ default: ({ children }: { children: React.ReactNode }) => <div>{children}</div> }));
vi.mock("@/components/Seo", () => ({ Seo: () => null }));
vi.mock("@/_core/hooks/useAuth", () => ({ useAuth: () => ({ isAuthenticated: true }) }));
vi.mock("@/components/ui/dialog", () => ({ Dialog: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogContent: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogDescription: ({ children }: { children: React.ReactNode }) => <p>{children}</p>, DialogFooter: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogHeader: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DialogTitle: ({ children }: { children: React.ReactNode }) => <h2>{children}</h2>, useDialogComposition: () => null }));
vi.mock("sonner", () => ({ toast: { error: vi.fn(), success: vi.fn() } }));
vi.mock("@/lib/trpc", () => ({ trpc: { useUtils: trpcMocks.useUtils, contacts: { list: { useQuery: trpcMocks.contactsListUseQuery } }, deals: { list: { useQuery: trpcMocks.dealsListUseQuery } }, documents: { list: { useQuery: trpcMocks.documentsListUseQuery }, create: { useMutation: trpcMocks.createUseMutation }, setStatus: { useMutation: trpcMocks.setStatusUseMutation } } } }));
import Documents from "../client/src/pages/Documents";
const create = vi.fn(); const setStatus = vi.fn();
beforeEach(() => { vi.clearAllMocks(); trpcMocks.useUtils.mockReturnValue({ documents: { list: { invalidate: vi.fn() } } }); trpcMocks.contactsListUseQuery.mockReturnValue({ data: [{ id: 81, displayName: "Tiffany Hoskins" }], isLoading: false }); trpcMocks.dealsListUseQuery.mockReturnValue({ data: [{ id: 91, title: "Main Street listing", contactName: "Tiffany Hoskins" }], isLoading: false }); trpcMocks.documentsListUseQuery.mockReturnValue({ data: [{ id: 401, name: "Seller disclosure package", documentType: "disclosure", status: "requested", dueAt: null, notes: null, contactName: "Tiffany Hoskins", dealTitle: "Main Street listing" }], isLoading: false }); trpcMocks.createUseMutation.mockReturnValue({ isPending: false, mutate: create }); trpcMocks.setStatusUseMutation.mockReturnValue({ isPending: false, mutate: setStatus }); });
afterEach(() => cleanup());
describe("Documents workspace", () => { it("creates a connected document tracking record", () => { render(<Documents />); fireEvent.change(screen.getByLabelText("Document name"), { target: { value: "Offer packet" } }); fireEvent.change(screen.getByLabelText(/^Contact/), { target: { value: "81" } }); fireEvent.change(screen.getByLabelText(/^Deal/), { target: { value: "91" } }); fireEvent.change(screen.getByLabelText("Document type"), { target: { value: "offer" } }); fireEvent.click(within(screen.getByLabelText("Document name").closest("form")!).getByRole("button", { name: "Create record" })); expect(create).toHaveBeenCalledWith(expect.objectContaining({ name: "Offer packet", contactId: 81, dealId: 91, documentType: "offer", status: "requested" })); }); it("renders connected context and submits a controlled status update", () => { render(<Documents />); expect(screen.getAllByText("Tiffany Hoskins").length).toBeGreaterThan(1); expect(screen.getByText("Main Street listing")).toBeTruthy(); fireEvent.change(screen.getByLabelText("Update status for Seller disclosure package"), { target: { value: "approved" } }); expect(setStatus).toHaveBeenCalledWith({ documentId: 401, status: "approved" }); }); });
