/* @vitest-environment jsdom */
import { cleanup, render, screen } from "@testing-library/react";
import React from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const trpcMocks = vi.hoisted(() => ({ overviewUseQuery: vi.fn() }));
vi.mock("@/components/DashboardLayout", () => ({ default: ({ children }: { children: React.ReactNode }) => <div>{children}</div> })); vi.mock("@/components/Seo", () => ({ Seo: () => null })); vi.mock("@/_core/hooks/useAuth", () => ({ useAuth: () => ({ isAuthenticated: true }) })); vi.mock("@/lib/trpc", () => ({ trpc: { reports: { overview: { useQuery: trpcMocks.overviewUseQuery } } } }));
import Reports from "../client/src/pages/Reports";
beforeEach(() => { trpcMocks.overviewUseQuery.mockReturnValue({ isLoading: false, isError: false, refetch: vi.fn(), data: { contactCount: 8, eligibleContactCount: 6, activeDealCount: 3, pipelineValueCents: 92500000, closedDealCount: 1, openTaskCount: 4, overdueTaskCount: 1, campaignPlanCount: 2, documentReviewCount: 3, stageCounts: [{ stage: "offer", count: 2, valueCents: 65000000 }], contactStatusCounts: [{ status: "prospect", count: 4 }] } }); }); afterEach(() => cleanup());
describe("Reports workspace", () => { it("renders calculated owner-scoped pipeline, task, and contact metrics", () => { render(<Reports />); expect(screen.getByText("$925,000")).toBeTruthy(); expect(screen.getByText("Across 3 open deals.")).toBeTruthy(); expect(screen.getByText("1 currently overdue.")).toBeTruthy(); expect(screen.getByText("Offer")).toBeTruthy(); expect(screen.getByText("Prospect")).toBeTruthy(); }); it("renders a recoverable error state instead of an indefinite loader", () => { trpcMocks.overviewUseQuery.mockReturnValue({ isLoading: false, isError: true, refetch: vi.fn(), data: undefined }); render(<Reports />); expect(screen.getByRole("alert").textContent).toContain("Reports unavailable"); expect(screen.getByRole("button", { name: "Try again" })).toBeTruthy(); }); it("renders an explicit missing-payload state", () => { trpcMocks.overviewUseQuery.mockReturnValue({ isLoading: false, isError: false, refetch: vi.fn(), data: undefined }); render(<Reports />); expect(screen.getByText("No reporting data is available yet.")).toBeTruthy(); }); });
